name: AstraVaultAI
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pyside6
  - cryptography
  - argon2-cffi
  - scikit-learn
  - numpy
  - sqlalchemy
  - watchdog
  - loguru
  - pytest
  - flake8
  - pyinstaller
  - nuitka
  - pycryptodomex
